### ISSUE TITLE
Might want a different license

### ISSUE THREAD

**Issue by virtuald** [NWChen/robotpy-logo#1]
Given that all of these files are images, and not software, the MIT license probably isn't the most appropriate license for it.

For a similar license that is meant for images, check out the Creative Commons family of licenses at http://creativecommons.org/choose/ .

I am not a lawyer, but I believe this is the closest in spirt to the MIT license: http://creativecommons.org/licenses/by/4.0/

**Comment by NWChen** [comment]
Good point - changed it to a CC license.
