### ISSUE TITLE
One more thought

### ISSUE THREAD

**Issue by virtuald** [NWChen/robotpy-logo#2]
Might want to export a square version of the logo, for things like avatars? I tried creating one and setting it as the robotpy organization logo (just go to https://github.com/robotpy and you should see it), and it's a bit small. Not sure if there's anything that can be done about that though, since it's a rectangular logo. 

This is really excellent work, thanks again!

**Comment by NWChen** [comment]
How's this? 
![image](https://cloud.githubusercontent.com/assets/2496616/5550110/6ee561b0-8b69-11e4-845d-73eb9143b5b0.png)

**Comment by virtuald** [comment]
I like it. Is it off-center slightly?

**Comment by NWChen** [comment]
It is, my bad. Here's one with both horizontally aligned.
![image](https://cloud.githubusercontent.com/assets/2496616/5551719/ca7c7b10-8bac-11e4-896c-fd261642911b.png)
It looks a little weird with the vertical parts of the "R" and "T" of ROBOT not at the same distance from the corners of the hexagon, but everything is spaced evenly from the edges of a bounding box.

**Comment by virtuald** [comment]
Hm. That's not very good either. I think if the left 'O' was centered over the corner, that would look better. Or maybe, if the text was centered based on the left edge of the R and the right edge of the center of the T.

**Comment by NWChen** [comment]
Yeah, I thought so too. Centering over the 'O' does seem better IMO:
![image](https://cloud.githubusercontent.com/assets/2496616/5553382/1b4b900e-8bed-11e4-9de2-b2c6c179a39c.png)

**Comment by virtuald** [comment]
That's excellent, thanks!
